
export const COLUMNS = [
  { id: 'no', title: 'NO' },
  { id: 'status', title: 'Süreç', fixed: true },
  { id: 'responsibleExpert', title: 'Sorumlu Uzman' },
  { id: 'province', title: 'İşyerinin Bulunduğu İl' },
  { id: 'branch', title: 'Bağlı Olduğu Şube' },
  { id: 'workplaceType', title: 'İşyeri Türü' },
  { id: 'name', title: 'İşyeri Adı' },
  { id: 'sgkNo', title: 'SGK No' },
  { id: 'employeeCount', title: 'İşçi Sayısı' },
  { id: 'memberCount', title: 'Üye Sayısı' },
  { id: 'employerUnion', title: 'İşveren Sendikası' },
  { id: 'tenderStartDate', title: 'İhale Başlangıç Tarihi' },
  { id: 'tenderEndDate', title: 'İhale Bitiş Tarihi' },
  { id: 'tenderName', title: 'İhale Adı' },
  { id: 'authorizationType', title: 'Yetki Belgesi Türü' },
  { id: 'authorizationDate', title: 'Yetki Tespit Tarihi' },
  { id: 'strikeStatus', title: 'Grev Yasağı Durumu' },
  { id: 'authorizationNoticeDate', title: 'Yetki Belgesi Tebliğ Tarihi' },
  { id: 'callDate', title: 'Çağrı Tarihi' },
  { id: 'placeAndDateDetermination', title: 'Yer ve Gün Tespit Tarihi' },
  { id: 'predeterminedFirstSession', title: 'Önceden Belirlenen İlk Oturum Tarihi' },
  { id: 'firstSessionDate', title: 'İlk Oturum Tarihi' },
  { id: 'disputeDate', title: 'Uyuşmazlık Tarihi' },
  { id: 'mediatorDeadline', title: 'Arabulucu Atama Son Tarih' },
  { id: 'mediatorReportDate', title: 'Arabulucu Raporu Tebliğ Tarihi' },
  { id: 'strikeDecisionDate', title: 'Grev Kararı Tarihi' },
  { id: 'actualStrikeDate', title: 'Fiili Grev Kararı Tarihi' },
  { id: 'strikeVotingDate', title: 'Grev Oylaması Tarihi' },
  { id: 'yhkSubmissionDate', title: 'YHK Gönderim Tarihi' },
  { id: 'yhkReminder', title: 'YHK Hatırlatma' },
  { id: 'tisSignDate', title: 'TİS İmza Tarihi' },
  { id: 'tisStartDate', title: 'TİS Başlangıç Tarihi' },
  { id: 'tisEndDate', title: 'TİS Bitiş Tarihi' }
] as const;
