// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckamzvmrkfkatbynwdom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrYW16dm1ya2ZrYXRieW53ZG9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMzYxMTEsImV4cCI6MjA2MDcxMjExMX0.F9Bbn0eEeGxdIwtExwusIOg1JMI-MvXTNR3HyfTy6Os";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);